export default defineEventHandler((event) => {
    let fakeNames = [
        "James",
        "Mary",
        "Robert",
        "Patricia",
        "John",
        "Jennifer",
        "Michael",
        "Linda",
        "David",
        "Elizabeth",
        "William",
        "Barbara",
        "Richard",
        "Susan",
        "Joseph",
        "Jessica",
        "Thomas",
        "Sarah",
        "Christopher",
        "Karen",
        "Charles",
        "Lisa",
        "Daniel",
        "Nancy",
        "Matthew",
        "Betty",
        "Anthony",
        "Sandra",
        "Mark",
        "Margaret",
        "Donald",
        "Ashley",
        "Steven",
        "Kimberly",
        "Andrew",
        "Emily",
        "Paul",
        "Donna",
        "Joshua",
        "Michelle",
    ];

    return Array.from({ length: 6 }, (item, i) => ({
        id: i + 1,
        image: helperPicture(),
        avatar: helperPicture(),
        isFavorite: Math.floor(Math.random() * i) % 2 === 0,
        name: fakeNames[i],
        text: "小花愛吃愛分享推薦！年度必買居家小物開箱，買完好過年度必買居家～",
    }));
});
