export default defineEventHandler((event) => {
    return [
        {
            id: 1,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 10,
            people: 330,
            achievementRate: 60,
            price: 300000,
            tags: [
                { name: "促銷", color: "primary", type: "text" },
                { name: "免運", color: "danger", type: "text" },
                { name: "獨家", color: "success", type: "text" },
            ],
        },
        {
            id: 2,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 3,
            people: 100,
            achievementRate: 100,
            price: 300000,
            tags: [
                { name: "促銷", color: "primary", type: "text" },
                { name: "免運", color: "danger", type: "text" },
            ],
        },
        {
            id: 3,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 5,
            people: 330,
            achievementRate: 300,
            price: 300000,
            tags: [{ name: "免運", color: "danger", type: "text" }],
        },
        {
            id: 4,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 100,
            people: 3,
            achievementRate: 3,
            price: 300000,
            tags: [
                { name: "促銷", color: "primary", type: "text" },
                { name: "免運", color: "danger", type: "text" },
                { name: "獨家", color: "success", type: "text" },
            ],
        },
        {
            id: 5,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 31,
            people: 1250,
            achievementRate: 50,
            price: 300000,
            tags: [],
        },
        {
            id: 6,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 1,
            people: 21,
            achievementRate: 100,
            price: 200,
            tags: [],
        },
        {
            id: 7,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 10,
            people: 201,
            achievementRate: 120,
            price: 333,
            tags: [],
        },
        {
            id: 8,
            image: helperPicture(),
            text: helperLorem(),
            dataTime: 10,
            people: 2111,
            achievementRate: 1200,
            price: 350000,
            tags: [
                { name: "促銷", color: "primary", type: "text" },
                { name: "免運", color: "danger", type: "text" },
                { name: "獨家", color: "success", type: "text" },
            ],
        },
    ];
});
